---
---
# Source: traefik/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-helm-chart
  labels:
    app: traefik
    chart: traefik-1.78.5
    release: "traefik-helm-chart"
    heritage: "Tiller"
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "info"
    defaultEntryPoints = ["http", "httpn"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
      [entryPoints.httpn]
      address = ":8880"
      compress = true
    [ping]
    entryPoint = "http"
    [kubernetes]
    [traefikLog]
      format = "json"

---

# Source: traefik/templates/tests/test-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-helm-chart-test
  labels:
    app: traefik-helm-chart
    chart: traefik-1.78.5
    heritage: "Tiller"
    release: "traefik-helm-chart"
data:
  run.sh: |-
    @test "Test Access" {
      curl -D - http://traefik-helm-chart/
    }


---

# Source: traefik/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik-helm-chart
  labels:
    app: traefik
    chart: traefik-1.78.5
    release: "traefik-helm-chart"
    heritage: "Tiller"
  annotations:
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: traefik
    release: traefik-helm-chart
  ports:
  - port: 80
    name: http
    targetPort: http
  - port: 443
    name: https
    targetPort: httpn
---

# Source: traefik/templates/tests/test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: traefik-helm-chart-test
  labels:
    app: traefik-helm-chart
    chart: traefik-1.78.5
    heritage: "Tiller"
    release: "traefik-helm-chart"
  annotations:
    "helm.sh/hook": test-success
spec:
  initContainers:
    - name: test-framework
      image: "dduportal/bats:0.4.0"
      command:
      - "bash"
      - "-c"
      - |
        set -ex
        # copy bats to tools dir
        cp -R /usr/local/libexec/ /tools/bats/
      volumeMounts:
      - mountPath: /tools
        name: tools
  containers:
    - name: traefik-helm-chart-test
      image: "dduportal/bats:0.4.0"
      command: ["/tools/bats/bats", "-t", "/tests/run.sh"]
      volumeMounts:
      - mountPath: /tests
        name: tests
        readOnly: true
      - mountPath: /tools
        name: tools
  volumes:
  - name: tests
    configMap:
      name: traefik-helm-chart-test
  - name: tools
    emptyDir: {}
  restartPolicy: Never

---

# Source: traefik/templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-helm-chart
  labels:
    app: traefik
    chart: traefik-1.78.5
    release: "traefik-helm-chart"
    heritage: "Tiller"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
      release: traefik-helm-chart
  template:
    metadata:
      annotations:
        checksum/config: 5aeac64c77d55c931f5fabed24e278e1b1bc343aad4fbf6c7bd29b6fdd47aafc
      labels:
        app: traefik
        chart: traefik-1.78.5
        release: "traefik-helm-chart"
        heritage: "Tiller"
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:1.7.14
        name: traefik-helm-chart
        resources:
          {}
          
        readinessProbe:
          httpGet:
            path: /ping
            port: "http"
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /ping
            port: "http"
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        volumeMounts:
        - mountPath: /config
          name: config
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: httpn
          containerPort: 8880
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        args:
        - --configfile=/config/traefik.toml

      volumes:
      - name: config
        configMap:
          name: traefik-helm-chart

