---
apiVersion: v1
kind: Namespace
metadata:
  name: jaeger
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
  name: zipkin
  namespace: jaeger
spec:
  ports:
  - name: http
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/component: collector
  type: ClusterIP

