---
---
# Source: jaeger-operator/templates/service-account.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: jaeger-jaeger-operator
  namespace: default
  labels:
    
    app.kubernetes.io/name: jaeger-operator
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: jaeger-operator-2.10.2

---

# Source: jaeger-operator/templates/crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jaegers.jaegertracing.io
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    
    app.kubernetes.io/name: jaeger-operator
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: jaeger-operator-2.10.2
spec:
  group: jaegertracing.io
  names:
    kind: Jaeger
    listKind: JaegerList
    plural: jaegers
    singular: jaeger
  scope: Namespaced
  version: v1
  versions:
    - name: v1
      served: true
      storage: true

---

# Source: jaeger-operator/templates/role.yaml

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jaeger-jaeger-operator
  namespace: default
  labels:
    
    app.kubernetes.io/name: jaeger-operator
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: jaeger-operator-2.10.2
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - io.jaegertracing
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - replicasets
  - deployments
  - daemonsets
  - statefulsets
  - ingresses
  verbs:
  - "*"
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - "*"
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - "*"
- apiGroups:
  - logging.openshift.io
  resources:
  - elasticsearches
  verbs:
  - '*'
- apiGroups:
  - jaegertracing.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - '*'
- apiGroups:
  - apps
  - extensions
  resourceNames:
  - jaeger-operator
  resources:
  - deployments/finalizers
  verbs:
  - update

---

# Source: jaeger-operator/templates/role-binding.yaml

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jaeger-jaeger-operator
  namespace: default
  labels:
    
    app.kubernetes.io/name: jaeger-operator
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: jaeger-operator-2.10.2
subjects:
- kind: ServiceAccount
  namespace: default
  name: jaeger-jaeger-operator
roleRef:
  kind: Role
  name: jaeger-jaeger-operator
  apiGroup: rbac.authorization.k8s.io

---

# Source: jaeger-operator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: jaeger-jaeger-operator-metrics
  labels:
    
    app.kubernetes.io/name: jaeger-operator
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: jaeger-operator-2.10.2
spec:
  ports:
  - name: metrics
    port: 8383
    protocol: TCP
    targetPort: 8383
  selector:
    app.kubernetes.io/name: jaeger-operator
    app.kubernetes.io/instance: jaeger
  type: ClusterIP

---

# Source: jaeger-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-jaeger-operator
  labels:
    
    app.kubernetes.io/name: jaeger-operator
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: jaeger-operator-2.10.2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger-operator
      app.kubernetes.io/instance: jaeger
  template:
    metadata:
      name: jaeger-jaeger-operator
      labels:
        
        app.kubernetes.io/name: jaeger-operator
        app.kubernetes.io/instance: jaeger
        app.kubernetes.io/managed-by: Tiller
        helm.sh/chart: jaeger-operator-2.10.2
    spec:
      serviceAccountName: jaeger-jaeger-operator
      containers:
        - name: jaeger-jaeger-operator
          image: "jaegertracing/jaeger-operator:1.14.0"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8383
            name: metrics
          args: ["start"]
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "jaeger-jaeger-operator"
          resources:
            {}
            

